// GENERATED by tools/moments.mjs from spec/mascot.json — do not edit by hand.
// Moment keys are the contract between code and the mascot: append-only, never renamed.
package com.dfeverx.studioshare.mascot

object MascotMoments {
    const val AccountContactSheet = "account.contactSheet"
    const val AccountEmailSent = "account.emailSent"
    const val AccountEmailTaken = "account.emailTaken"
    const val AccountLinked = "account.linked"
    const val AccountNudge = "account.nudge"
    const val AccountNudgeDismissed = "account.nudgeDismissed"
    const val AccountRecentLogin = "account.recentLogin"
    const val AccountSwitch = "account.switch"
    const val AppActivity = "app.activity"
    const val AppIdle = "app.idle"
    const val AppLateNight = "app.lateNight"
    const val AppLaunch = "app.launch"
    const val AppLongIdle = "app.longIdle"
    const val AppNavigated = "app.navigated"
    const val AppResumed = "app.resumed"
    const val AppTapped = "app.tapped"
    const val AppWelcomeBack = "app.welcomeBack"
    const val AttendeesAddManual = "attendees.addManual"
    const val AttendeesDedupe = "attendees.dedupe"
    const val AttendeesEmpty = "attendees.empty"
    const val AttendeesError = "attendees.error"
    const val AttendeesFaceProblem = "attendees.faceProblem"
    const val AttendeesFacesOk = "attendees.facesOk"
    const val AttendeesFacesReading = "attendees.facesReading"
    const val AttendeesImportPicker = "attendees.importPicker"
    const val AttendeesImported = "attendees.imported"
    const val AttendeesImporting = "attendees.importing"
    const val AttendeesMapColumns = "attendees.mapColumns"
    const val AttendeesMatched = "attendees.matched"
    const val AttendeesMatching = "attendees.matching"
    const val AttendeesNoFaces = "attendees.noFaces"
    const val AttendeesNoResults = "attendees.noResults"
    const val AttendeesParseError = "attendees.parseError"
    const val AttendeesPublishFirst = "attendees.publishFirst"
    const val AttendeesRemoved = "attendees.removed"
    const val AttendeesRoleGate = "attendees.roleGate"
    const val AttendeesWrongFile = "attendees.wrongFile"
    const val AuthBrowserWaiting = "auth.browserWaiting"
    const val AuthCancelled = "auth.cancelled"
    const val AuthLaunchingStudio = "auth.launchingStudio"
    const val AuthNewUser = "auth.newUser"
    const val AuthOtp = "auth.otp"
    const val AuthPhone = "auth.phone"
    const val AuthPhoneInvalid = "auth.phoneInvalid"
    const val AuthProviderOpening = "auth.providerOpening"
    const val AuthResendAvailable = "auth.resendAvailable"
    const val AuthResendCountdown = "auth.resendCountdown"
    const val AuthRestartConfirm = "auth.restartConfirm"
    const val AuthSendingCode = "auth.sendingCode"
    const val AuthSignOut = "auth.signOut"
    const val AuthSignedIn = "auth.signedIn"
    const val AuthSlugAvailable = "auth.slugAvailable"
    const val AuthSlugTaken = "auth.slugTaken"
    const val AuthStudioLaunched = "auth.studioLaunched"
    const val AuthStudioName = "auth.studioName"
    const val AuthTermsMissing = "auth.termsMissing"
    const val AuthTermsTicked = "auth.termsTicked"
    const val AuthTooManyAttempts = "auth.tooManyAttempts"
    const val AuthVerifying = "auth.verifying"
    const val AuthWelcome = "auth.welcome"
    const val AuthWrongCode = "auth.wrongCode"
    const val BadgeAwaitingPhotos = "badge.awaitingPhotos"
    const val BadgeCullPending = "badge.cullPending"
    const val BadgeExportReady = "badge.exportReady"
    const val BadgeInvited = "badge.invited"
    const val BadgeNew = "badge.new"
    const val BadgeReadyToShare = "badge.readyToShare"
    const val BadgeReselecting = "badge.reselecting"
    const val BadgeSelecting = "badge.selecting"
    const val BadgeShooting = "badge.shooting"
    const val BadgeUpcoming = "badge.upcoming"
    const val BadgeUploading = "badge.uploading"
    const val BillingFreeTier = "billing.freeTier"
    const val BillingNoPlans = "billing.noPlans"
    const val BillingNothingToRestore = "billing.nothingToRestore"
    const val BillingOtherDevice = "billing.otherDevice"
    const val BillingPaywall = "billing.paywall"
    const val BillingPurchased = "billing.purchased"
    const val BillingRestoring = "billing.restoring"
    const val BillingSubscribed = "billing.subscribed"
    const val BookingFormClosed = "bookingForm.closed"
    const val BookingFormDirty = "bookingForm.dirty"
    const val BookingFormInvalid = "bookingForm.invalid"
    const val BookingFormOpen = "bookingForm.open"
    const val BookingFormSaved = "bookingForm.saved"
    const val CampaignDelivered = "campaign.delivered"
    const val CampaignEditing = "campaign.editing"
    const val CampaignInline = "campaign.inline"
    const val CampaignLogEmpty = "campaign.logEmpty"
    const val CampaignSaved = "campaign.saved"
    const val CampaignSending = "campaign.sending"
    const val CampaignSomeFailed = "campaign.someFailed"
    const val CampaignTest = "campaign.test"
    const val CaptureBrandPicker = "capture.brandPicker"
    const val CaptureBurst = "capture.burst"
    const val CaptureCameraFound = "capture.cameraFound"
    const val CaptureConnectNow = "capture.connectNow"
    const val CaptureEntry = "capture.entry"
    const val CaptureExactValues = "capture.exactValues"
    const val CaptureFirewall = "capture.firewall"
    const val CaptureFirstPhoto = "capture.firstPhoto"
    const val CaptureHintValues = "capture.hintValues"
    const val CaptureHintWifi = "capture.hintWifi"
    const val CaptureHostChanged = "capture.hostChanged"
    const val CaptureHotspot = "capture.hotspot"
    const val CaptureHotspotChecking = "capture.hotspotChecking"
    const val CaptureLeaveWarning = "capture.leaveWarning"
    const val CaptureLive = "capture.live"
    const val CaptureLockedOut = "capture.lockedOut"
    const val CaptureLost = "capture.lost"
    const val CaptureNeedsCredits = "capture.needsCredits"
    const val CaptureNotifyAsk = "capture.notifyAsk"
    const val CapturePassiveOff = "capture.passiveOff"
    const val CapturePasswordStep = "capture.passwordStep"
    const val CaptureProblem = "capture.problem"
    const val CaptureQuiet = "capture.quiet"
    const val CaptureReconnectKnown = "capture.reconnectKnown"
    const val CaptureReconnected = "capture.reconnected"
    const val CaptureSecureMode = "capture.secureMode"
    const val CaptureSetup = "capture.setup"
    const val CaptureSignedIn = "capture.signedIn"
    const val CaptureStopConfirm = "capture.stopConfirm"
    const val CaptureStopped = "capture.stopped"
    const val CaptureTransferFailed = "capture.transferFailed"
    const val CaptureVerified = "capture.verified"
    const val CaptureWaitingForCamera = "capture.waitingForCamera"
    const val CaptureWrongPassword = "capture.wrongPassword"
    const val CaptureWrongUser = "capture.wrongUser"
    const val CloudTabEmpty = "cloud.tabEmpty"
    const val CreditsExpired = "credits.expired"
    const val CreditsUnverified = "credits.unverified"
    const val CrewAssigned = "crew.assigned"
    const val CrewEmpty = "crew.empty"
    const val CrewInfo = "crew.info"
    const val CullAgain = "cull.again"
    const val CullAiCull = "cull.aiCull"
    const val CullAllDecided = "cull.allDecided"
    const val CullAssisted = "cull.assisted"
    const val CullBulkRated = "cull.bulkRated"
    const val CullChoose = "cull.choose"
    const val CullCompareDone = "cull.compareDone"
    const val CullDraftWait = "cull.draftWait"
    const val CullEmpty = "cull.empty"
    const val CullExport = "cull.export"
    const val CullExportBusy = "cull.exportBusy"
    const val CullHighlights = "cull.highlights"
    const val CullHot = "cull.hot"
    const val CullIntro = "cull.intro"
    const val CullJudging = "cull.judging"
    const val CullKeepOpen = "cull.keepOpen"
    const val CullKeyHelp = "cull.keyHelp"
    const val CullModelsDownloading = "cull.modelsDownloading"
    const val CullModelsFailed = "cull.modelsFailed"
    const val CullModelsOffline = "cull.modelsOffline"
    const val CullModelsPreparing = "cull.modelsPreparing"
    const val CullNothingChecked = "cull.nothingChecked"
    const val CullNothingKept = "cull.nothingKept"
    const val CullOpened = "cull.opened"
    const val CullPaused = "cull.paused"
    const val CullReleaseFailed = "cull.releaseFailed"
    const val CullRestart = "cull.restart"
    const val CullReview = "cull.review"
    const val CullRowBlurred = "cull.rowBlurred"
    const val CullRowClosedEyes = "cull.rowClosedEyes"
    const val CullRowDuplicate = "cull.rowDuplicate"
    const val CullRowFlagged = "cull.rowFlagged"
    const val CullRowLowerRanked = "cull.rowLowerRanked"
    const val CullRowMaybe = "cull.rowMaybe"
    const val CullRowSelected = "cull.rowSelected"
    const val CullRunning = "cull.running"
    const val CullScanning = "cull.scanning"
    const val CullSendDialog = "cull.sendDialog"
    const val CullSendMaybes = "cull.sendMaybes"
    const val CullSent = "cull.sent"
    const val CullStarted = "cull.started"
    const val CullStrictness = "cull.strictness"
    const val CullStyles = "cull.styles"
    const val CullTabEmpty = "cull.tabEmpty"
    const val CullTarget = "cull.target"
    const val CullUploadConfirm = "cull.uploadConfirm"
    const val DeviceHot = "device.hot"
    const val DiagnosticsConsent = "diagnostics.consent"
    const val DiagnosticsSent = "diagnostics.sent"
    const val EventCorporateLocked = "event.corporateLocked"
    const val EventCoverAdded = "event.coverAdded"
    const val EventCoverFailed = "event.coverFailed"
    const val EventCreateForm = "event.createForm"
    const val EventCrewAssigned = "event.crewAssigned"
    const val EventDateSet = "event.dateSet"
    const val EventDayAdded = "event.dayAdded"
    const val EventDayRemoved = "event.dayRemoved"
    const val EventDeleteConfirm = "event.deleteConfirm"
    const val EventDeleted = "event.deleted"
    const val EventDraftFailed = "event.draftFailed"
    const val EventDraftSaved = "event.draftSaved"
    const val EventEdited = "event.edited"
    const val EventNameTyping = "event.nameTyping"
    const val EventNeedsDate = "event.needsDate"
    const val EventOutOfCredits = "event.outOfCredits"
    const val EventPublishConfirm = "event.publishConfirm"
    const val EventPublishFailed = "event.publishFailed"
    const val EventPublished = "event.published"
    const val EventPublishing = "event.publishing"
    const val EventRetentionSet = "event.retentionSet"
    const val EventTypeChosen = "event.typeChosen"
    const val EventsEmpty = "events.empty"
    const val EventsError = "events.error"
    const val EventsFound = "events.found"
    const val EventsNoneCompleted = "events.noneCompleted"
    const val EventsNoneInMonth = "events.noneInMonth"
    const val EventsRefresh = "events.refresh"
    const val ExportAlreadyDone = "export.alreadyDone"
    const val ExportDone = "export.done"
    const val ExportFailed = "export.failed"
    const val ExportMissingOriginals = "export.missingOriginals"
    const val ExportPartial = "export.partial"
    const val ExportPreparing = "export.preparing"
    const val ExportRunning = "export.running"
    const val ExportStopped = "export.stopped"
    const val ExportStructure = "export.structure"
    const val FacesAllMatched = "faces.allMatched"
    const val FacesExhausted = "faces.exhausted"
    const val FacesFailed = "faces.failed"
    const val FacesMatched = "faces.matched"
    const val FacesMatching = "faces.matching"
    const val FacesNoMatches = "faces.noMatches"
    const val FacesNone = "faces.none"
    const val FacesReading = "faces.reading"
    const val FacesRetentionInfo = "faces.retentionInfo"
    const val FailedEmpty = "failed.empty"
    const val FolderAddToPublished = "folder.addToPublished"
    const val FolderCreated = "folder.created"
    const val FolderDropHover = "folder.dropHover"
    const val FolderEmpty = "folder.empty"
    const val FolderPinned = "folder.pinned"
    const val FolderRenamed = "folder.renamed"
    const val FolderTypeChosen = "folder.typeChosen"
    const val FoldersEmpty = "folders.empty"
    const val HostsAccessOff = "hosts.accessOff"
    const val HostsAccessOn = "hosts.accessOn"
    const val HostsContacts = "hosts.contacts"
    const val HostsDuplicate = "hosts.duplicate"
    const val HostsEmpty = "hosts.empty"
    const val HostsFailed = "hosts.failed"
    const val HostsInviteEmail = "hosts.inviteEmail"
    const val HostsInviteLink = "hosts.inviteLink"
    const val HostsInvitePhone = "hosts.invitePhone"
    const val HostsInviteSent = "hosts.inviteSent"
    const val HostsJoined = "hosts.joined"
    const val HostsLinkCreated = "hosts.linkCreated"
    const val HostsLinkExpired = "hosts.linkExpired"
    const val HostsLinkExtended = "hosts.linkExtended"
    const val HostsLinkFull = "hosts.linkFull"
    const val HostsPending = "hosts.pending"
    const val HostsPublishFirst = "hosts.publishFirst"
    const val HostsRemoveConfirm = "hosts.removeConfirm"
    const val HostsRemoved = "hosts.removed"
    const val HostsResent = "hosts.resent"
    const val HostsRevokeConfirm = "hosts.revokeConfirm"
    const val HostsRevoked = "hosts.revoked"
    const val HostsSeats = "hosts.seats"
    const val HostsTtl = "hosts.ttl"
    const val ImportCancelConfirm = "import.cancelConfirm"
    const val ImportCopying = "import.copying"
    const val ImportCullChosen = "import.cullChosen"
    const val ImportDenied = "import.denied"
    const val ImportDiskFull = "import.diskFull"
    const val ImportDone = "import.done"
    const val ImportDriveLost = "import.driveLost"
    const val ImportDriveOut = "import.driveOut"
    const val ImportDuplicateName = "import.duplicateName"
    const val ImportFailed = "import.failed"
    const val ImportFileMissing = "import.fileMissing"
    const val ImportMenu = "import.menu"
    const val ImportOriginalsRead = "import.originalsRead"
    const val ImportPickerCancelled = "import.pickerCancelled"
    const val ImportPickerOpen = "import.pickerOpen"
    const val ImportQueued = "import.queued"
    const val ImportReadingOriginals = "import.readingOriginals"
    const val ImportRecheck = "import.recheck"
    const val ImportReview = "import.review"
    const val ImportTileLeftOut = "import.tileLeftOut"
    const val ImportTruncated = "import.truncated"
    const val ImportWithoutCull = "import.withoutCull"
    const val JobDelivered = "job.delivered"
    const val MediaLocateOriginals = "media.locateOriginals"
    const val OrbitBalanceDue = "orbit.balanceDue"
    const val OrbitBookingSeen = "orbit.bookingSeen"
    const val OrbitChipEmpty = "orbit.chipEmpty"
    const val OrbitCloseable = "orbit.closeable"
    const val OrbitCreateEvent = "orbit.createEvent"
    const val OrbitDatesConfirmed = "orbit.datesConfirmed"
    const val OrbitDeclined = "orbit.declined"
    const val OrbitDeleteConfirm = "orbit.deleteConfirm"
    const val OrbitDiscardConfirm = "orbit.discardConfirm"
    const val OrbitEditing = "orbit.editing"
    const val OrbitEmpty = "orbit.empty"
    const val OrbitEventLinked = "orbit.eventLinked"
    const val OrbitFollowUp = "orbit.followUp"
    const val OrbitHistoryEmpty = "orbit.historyEmpty"
    const val OrbitInvoiceDraft = "orbit.invoiceDraft"
    const val OrbitInvoiceSent = "orbit.invoiceSent"
    const val OrbitJobRestored = "orbit.jobRestored"
    const val OrbitMoneyWarning = "orbit.moneyWarning"
    const val OrbitNewBooking = "orbit.newBooking"
    const val OrbitNewJob = "orbit.newJob"
    const val OrbitNoteAdded = "orbit.noteAdded"
    const val OrbitPaidInFull = "orbit.paidInFull"
    const val OrbitPaymentFuture = "orbit.paymentFuture"
    const val OrbitPaymentRecorded = "orbit.paymentRecorded"
    const val OrbitPaymentTooMuch = "orbit.paymentTooMuch"
    const val OrbitPushOpened = "orbit.pushOpened"
    const val OrbitQuoteAccepted = "orbit.quoteAccepted"
    const val OrbitQuoteSent = "orbit.quoteSent"
    const val OrbitReceived = "orbit.received"
    const val OrbitRemovePaymentConfirm = "orbit.removePaymentConfirm"
    const val OrbitSyncFailed = "orbit.syncFailed"
    const val OrbitTrashEmpty = "orbit.trashEmpty"
    const val OrbitVoidConfirm = "orbit.voidConfirm"
    const val PermissionDeclined = "permission.declined"
    const val PermissionNotifications = "permission.notifications"
    const val PermissionPhotos = "permission.photos"
    const val ProcessingFailed = "processing.failed"
    const val PublicDownloads = "public.downloads"
    const val PublicExpired = "public.expired"
    const val PublicOff = "public.off"
    const val PublicOffline = "public.offline"
    const val PublicRefresh = "public.refresh"
    const val QrMapFailed = "qr.mapFailed"
    const val QrMapped = "qr.mapped"
    const val QrMapping = "qr.mapping"
    const val QrNoneAvailable = "qr.noneAvailable"
    const val QrNotMapped = "qr.notMapped"
    const val QrdirectCountdown = "qrdirect.countdown"
    const val QrdirectExpired = "qrdirect.expired"
    const val QrdirectGenerating = "qrdirect.generating"
    const val QrdirectReady = "qrdirect.ready"
    const val RoleGate = "role.gate"
    const val SelectionCompleted = "selection.completed"
    const val SelectionHostDone = "selection.hostDone"
    const val SelectionInProgress = "selection.inProgress"
    const val SelectionInvited = "selection.invited"
    const val SelectionLinkFirst = "selection.linkFirst"
    const val SelectionMaxChanged = "selection.maxChanged"
    const val SelectionMaxSet = "selection.maxSet"
    const val SelectionModerate = "selection.moderate"
    const val SelectionNotStarted = "selection.notStarted"
    const val SelectionPicks = "selection.picks"
    const val SelectionReselect = "selection.reselect"
    const val SelectionReset = "selection.reset"
    const val SelectionResetConfirm = "selection.resetConfirm"
    const val SelectionReviewAsk = "selection.reviewAsk"
    const val SelectionReviewReceived = "selection.reviewReceived"
    const val SelectionSeveral = "selection.several"
    const val SelectionStarted = "selection.started"
    const val SelectionUnfinishedWarning = "selection.unfinishedWarning"
    const val ShareCopied = "share.copied"
    const val ShareLink = "share.link"
    const val SharePublicConfirm = "share.publicConfirm"
    const val SharePublicLive = "share.publicLive"
    const val ShareQr = "share.qr"
    const val ShareQrSaveFailed = "share.qrSaveFailed"
    const val ShareQrSaved = "share.qrSaved"
    const val StateBackOnline = "state.backOnline"
    const val StateClientError = "state.clientError"
    const val StateCopied = "state.copied"
    const val StateDeleted = "state.deleted"
    const val StateDone = "state.done"
    const val StateEmpty = "state.empty"
    const val StateError = "state.error"
    const val StateInfo = "state.info"
    const val StateLoadingSlow = "state.loadingSlow"
    const val StateNoResults = "state.noResults"
    const val StateNothingSelected = "state.nothingSelected"
    const val StateOffline = "state.offline"
    const val StateOfflineSurface = "state.offlineSurface"
    const val StatePermission = "state.permission"
    const val StateSaved = "state.saved"
    const val StateSent = "state.sent"
    const val StateServerError = "state.serverError"
    const val StateSessionExpired = "state.sessionExpired"
    const val StateTimeout = "state.timeout"
    const val StateUndo = "state.undo"
    const val StateValidation = "state.validation"
    const val StateWarning = "state.warning"
    const val StorageCleanFailed = "storage.cleanFailed"
    const val StorageCleaned = "storage.cleaned"
    const val StorageEmpty = "storage.empty"
    const val StorageOpen = "storage.open"
    const val StorageUnavailable = "storage.unavailable"
    const val StudioAssetFailed = "studio.assetFailed"
    const val StudioCountry = "studio.country"
    const val StudioDetails = "studio.details"
    const val StudioLogo = "studio.logo"
    const val StudioNone = "studio.none"
    const val StudioOneLogo = "studio.oneLogo"
    const val TeamAddFailed = "team.addFailed"
    const val TeamAddForm = "team.addForm"
    const val TeamDuplicate = "team.duplicate"
    const val TeamEmpty = "team.empty"
    const val TeamMemberAdded = "team.memberAdded"
    const val TeamRefresh = "team.refresh"
    const val TeamRemoveConfirm = "team.removeConfirm"
    const val TeamRemoveOffline = "team.removeOffline"
    const val TeamRolePicker = "team.rolePicker"
    const val TransfersEmpty = "transfers.empty"
    const val UpdateAvailable = "update.available"
    const val UpdateCheckFailed = "update.checkFailed"
    const val UpdateDownloading = "update.downloading"
    const val UpdateLater = "update.later"
    const val UpdateReady = "update.ready"
    const val UpdateRequired = "update.required"
    const val UpdateUpToDate = "update.upToDate"
    const val UploadBackOnline = "upload.backOnline"
    const val UploadBackground = "upload.background"
    const val UploadBackgroundAsk = "upload.backgroundAsk"
    const val UploadCreditsLow = "upload.creditsLow"
    const val UploadDone = "upload.done"
    const val UploadFacesReading = "upload.facesReading"
    const val UploadFacesReady = "upload.facesReady"
    const val UploadFailed = "upload.failed"
    const val UploadKeepOpen = "upload.keepOpen"
    const val UploadManyFailed = "upload.manyFailed"
    const val UploadMorePreparing = "upload.morePreparing"
    const val UploadNoWatermark = "upload.noWatermark"
    const val UploadOffline = "upload.offline"
    const val UploadOutOfCredits = "upload.outOfCredits"
    const val UploadPaused = "upload.paused"
    const val UploadPausedByUser = "upload.pausedByUser"
    const val UploadPreparing = "upload.preparing"
    const val UploadResumed = "upload.resumed"
    const val UploadRetryAll = "upload.retryAll"
    const val UploadRetrying = "upload.retrying"
    const val UploadSlow = "upload.slow"
    const val UploadUploading = "upload.uploading"
    const val UploadWatermarking = "upload.watermarking"
    const val WallCover = "wall.cover"
    const val WallCoverFailed = "wall.coverFailed"
    const val WallEmpty = "wall.empty"
    const val WallFailed = "wall.failed"
    const val WallFeatured = "wall.featured"
    const val WallPublishConfirm = "wall.publishConfirm"
    const val WallPublished = "wall.published"
    const val WallStyling = "wall.styling"
    const val WallUnpublished = "wall.unpublished"
    const val WatermarkEditing = "watermark.editing"
    const val WatermarkEnabled = "watermark.enabled"
    const val WatermarkSaved = "watermark.saved"
    const val WebsiteAiFailed = "website.aiFailed"
    const val WebsiteAiLimit = "website.aiLimit"
    const val WebsiteAiUnavailable = "website.aiUnavailable"
    const val WebsiteAiUndone = "website.aiUndone"
    const val WebsiteAiWriting = "website.aiWriting"
    const val WebsiteAiWritten = "website.aiWritten"
    const val WebsiteAlbumSaved = "website.albumSaved"
    const val WebsiteAlbumUploading = "website.albumUploading"
    const val WebsiteAlbumsEmpty = "website.albumsEmpty"
    const val WebsiteChecklist = "website.checklist"
    const val WebsiteDesigning = "website.designing"
    const val WebsiteDirty = "website.dirty"
    const val WebsiteDiscard = "website.discard"
    const val WebsiteFaviconPending = "website.faviconPending"
    const val WebsiteLive = "website.live"
    const val WebsiteLiveFailed = "website.liveFailed"
    const val WebsiteOffline = "website.offline"
    const val WebsitePublished = "website.published"
    const val WebsitePublishing = "website.publishing"
    const val WebsiteRedesign = "website.redesign"
    const val WebsiteUseDesign = "website.useDesign"
    const val WebsiteWizard = "website.wizard"

    val all: List<String> = listOf(
        "account.contactSheet",
        "account.emailSent",
        "account.emailTaken",
        "account.linked",
        "account.nudge",
        "account.nudgeDismissed",
        "account.recentLogin",
        "account.switch",
        "app.activity",
        "app.idle",
        "app.lateNight",
        "app.launch",
        "app.longIdle",
        "app.navigated",
        "app.resumed",
        "app.tapped",
        "app.welcomeBack",
        "attendees.addManual",
        "attendees.dedupe",
        "attendees.empty",
        "attendees.error",
        "attendees.faceProblem",
        "attendees.facesOk",
        "attendees.facesReading",
        "attendees.importPicker",
        "attendees.imported",
        "attendees.importing",
        "attendees.mapColumns",
        "attendees.matched",
        "attendees.matching",
        "attendees.noFaces",
        "attendees.noResults",
        "attendees.parseError",
        "attendees.publishFirst",
        "attendees.removed",
        "attendees.roleGate",
        "attendees.wrongFile",
        "auth.browserWaiting",
        "auth.cancelled",
        "auth.launchingStudio",
        "auth.newUser",
        "auth.otp",
        "auth.phone",
        "auth.phoneInvalid",
        "auth.providerOpening",
        "auth.resendAvailable",
        "auth.resendCountdown",
        "auth.restartConfirm",
        "auth.sendingCode",
        "auth.signOut",
        "auth.signedIn",
        "auth.slugAvailable",
        "auth.slugTaken",
        "auth.studioLaunched",
        "auth.studioName",
        "auth.termsMissing",
        "auth.termsTicked",
        "auth.tooManyAttempts",
        "auth.verifying",
        "auth.welcome",
        "auth.wrongCode",
        "badge.awaitingPhotos",
        "badge.cullPending",
        "badge.exportReady",
        "badge.invited",
        "badge.new",
        "badge.readyToShare",
        "badge.reselecting",
        "badge.selecting",
        "badge.shooting",
        "badge.upcoming",
        "badge.uploading",
        "billing.freeTier",
        "billing.noPlans",
        "billing.nothingToRestore",
        "billing.otherDevice",
        "billing.paywall",
        "billing.purchased",
        "billing.restoring",
        "billing.subscribed",
        "bookingForm.closed",
        "bookingForm.dirty",
        "bookingForm.invalid",
        "bookingForm.open",
        "bookingForm.saved",
        "campaign.delivered",
        "campaign.editing",
        "campaign.inline",
        "campaign.logEmpty",
        "campaign.saved",
        "campaign.sending",
        "campaign.someFailed",
        "campaign.test",
        "capture.brandPicker",
        "capture.burst",
        "capture.cameraFound",
        "capture.connectNow",
        "capture.entry",
        "capture.exactValues",
        "capture.firewall",
        "capture.firstPhoto",
        "capture.hintValues",
        "capture.hintWifi",
        "capture.hostChanged",
        "capture.hotspot",
        "capture.hotspotChecking",
        "capture.leaveWarning",
        "capture.live",
        "capture.lockedOut",
        "capture.lost",
        "capture.needsCredits",
        "capture.notifyAsk",
        "capture.passiveOff",
        "capture.passwordStep",
        "capture.problem",
        "capture.quiet",
        "capture.reconnectKnown",
        "capture.reconnected",
        "capture.secureMode",
        "capture.setup",
        "capture.signedIn",
        "capture.stopConfirm",
        "capture.stopped",
        "capture.transferFailed",
        "capture.verified",
        "capture.waitingForCamera",
        "capture.wrongPassword",
        "capture.wrongUser",
        "cloud.tabEmpty",
        "credits.expired",
        "credits.unverified",
        "crew.assigned",
        "crew.empty",
        "crew.info",
        "cull.again",
        "cull.aiCull",
        "cull.allDecided",
        "cull.assisted",
        "cull.bulkRated",
        "cull.choose",
        "cull.compareDone",
        "cull.draftWait",
        "cull.empty",
        "cull.export",
        "cull.exportBusy",
        "cull.highlights",
        "cull.hot",
        "cull.intro",
        "cull.judging",
        "cull.keepOpen",
        "cull.keyHelp",
        "cull.modelsDownloading",
        "cull.modelsFailed",
        "cull.modelsOffline",
        "cull.modelsPreparing",
        "cull.nothingChecked",
        "cull.nothingKept",
        "cull.opened",
        "cull.paused",
        "cull.releaseFailed",
        "cull.restart",
        "cull.review",
        "cull.rowBlurred",
        "cull.rowClosedEyes",
        "cull.rowDuplicate",
        "cull.rowFlagged",
        "cull.rowLowerRanked",
        "cull.rowMaybe",
        "cull.rowSelected",
        "cull.running",
        "cull.scanning",
        "cull.sendDialog",
        "cull.sendMaybes",
        "cull.sent",
        "cull.started",
        "cull.strictness",
        "cull.styles",
        "cull.tabEmpty",
        "cull.target",
        "cull.uploadConfirm",
        "device.hot",
        "diagnostics.consent",
        "diagnostics.sent",
        "event.corporateLocked",
        "event.coverAdded",
        "event.coverFailed",
        "event.createForm",
        "event.crewAssigned",
        "event.dateSet",
        "event.dayAdded",
        "event.dayRemoved",
        "event.deleteConfirm",
        "event.deleted",
        "event.draftFailed",
        "event.draftSaved",
        "event.edited",
        "event.nameTyping",
        "event.needsDate",
        "event.outOfCredits",
        "event.publishConfirm",
        "event.publishFailed",
        "event.published",
        "event.publishing",
        "event.retentionSet",
        "event.typeChosen",
        "events.empty",
        "events.error",
        "events.found",
        "events.noneCompleted",
        "events.noneInMonth",
        "events.refresh",
        "export.alreadyDone",
        "export.done",
        "export.failed",
        "export.missingOriginals",
        "export.partial",
        "export.preparing",
        "export.running",
        "export.stopped",
        "export.structure",
        "faces.allMatched",
        "faces.exhausted",
        "faces.failed",
        "faces.matched",
        "faces.matching",
        "faces.noMatches",
        "faces.none",
        "faces.reading",
        "faces.retentionInfo",
        "failed.empty",
        "folder.addToPublished",
        "folder.created",
        "folder.dropHover",
        "folder.empty",
        "folder.pinned",
        "folder.renamed",
        "folder.typeChosen",
        "folders.empty",
        "hosts.accessOff",
        "hosts.accessOn",
        "hosts.contacts",
        "hosts.duplicate",
        "hosts.empty",
        "hosts.failed",
        "hosts.inviteEmail",
        "hosts.inviteLink",
        "hosts.invitePhone",
        "hosts.inviteSent",
        "hosts.joined",
        "hosts.linkCreated",
        "hosts.linkExpired",
        "hosts.linkExtended",
        "hosts.linkFull",
        "hosts.pending",
        "hosts.publishFirst",
        "hosts.removeConfirm",
        "hosts.removed",
        "hosts.resent",
        "hosts.revokeConfirm",
        "hosts.revoked",
        "hosts.seats",
        "hosts.ttl",
        "import.cancelConfirm",
        "import.copying",
        "import.cullChosen",
        "import.denied",
        "import.diskFull",
        "import.done",
        "import.driveLost",
        "import.driveOut",
        "import.duplicateName",
        "import.failed",
        "import.fileMissing",
        "import.menu",
        "import.originalsRead",
        "import.pickerCancelled",
        "import.pickerOpen",
        "import.queued",
        "import.readingOriginals",
        "import.recheck",
        "import.review",
        "import.tileLeftOut",
        "import.truncated",
        "import.withoutCull",
        "job.delivered",
        "media.locateOriginals",
        "orbit.balanceDue",
        "orbit.bookingSeen",
        "orbit.chipEmpty",
        "orbit.closeable",
        "orbit.createEvent",
        "orbit.datesConfirmed",
        "orbit.declined",
        "orbit.deleteConfirm",
        "orbit.discardConfirm",
        "orbit.editing",
        "orbit.empty",
        "orbit.eventLinked",
        "orbit.followUp",
        "orbit.historyEmpty",
        "orbit.invoiceDraft",
        "orbit.invoiceSent",
        "orbit.jobRestored",
        "orbit.moneyWarning",
        "orbit.newBooking",
        "orbit.newJob",
        "orbit.noteAdded",
        "orbit.paidInFull",
        "orbit.paymentFuture",
        "orbit.paymentRecorded",
        "orbit.paymentTooMuch",
        "orbit.pushOpened",
        "orbit.quoteAccepted",
        "orbit.quoteSent",
        "orbit.received",
        "orbit.removePaymentConfirm",
        "orbit.syncFailed",
        "orbit.trashEmpty",
        "orbit.voidConfirm",
        "permission.declined",
        "permission.notifications",
        "permission.photos",
        "processing.failed",
        "public.downloads",
        "public.expired",
        "public.off",
        "public.offline",
        "public.refresh",
        "qr.mapFailed",
        "qr.mapped",
        "qr.mapping",
        "qr.noneAvailable",
        "qr.notMapped",
        "qrdirect.countdown",
        "qrdirect.expired",
        "qrdirect.generating",
        "qrdirect.ready",
        "role.gate",
        "selection.completed",
        "selection.hostDone",
        "selection.inProgress",
        "selection.invited",
        "selection.linkFirst",
        "selection.maxChanged",
        "selection.maxSet",
        "selection.moderate",
        "selection.notStarted",
        "selection.picks",
        "selection.reselect",
        "selection.reset",
        "selection.resetConfirm",
        "selection.reviewAsk",
        "selection.reviewReceived",
        "selection.several",
        "selection.started",
        "selection.unfinishedWarning",
        "share.copied",
        "share.link",
        "share.publicConfirm",
        "share.publicLive",
        "share.qr",
        "share.qrSaveFailed",
        "share.qrSaved",
        "state.backOnline",
        "state.clientError",
        "state.copied",
        "state.deleted",
        "state.done",
        "state.empty",
        "state.error",
        "state.info",
        "state.loadingSlow",
        "state.noResults",
        "state.nothingSelected",
        "state.offline",
        "state.offlineSurface",
        "state.permission",
        "state.saved",
        "state.sent",
        "state.serverError",
        "state.sessionExpired",
        "state.timeout",
        "state.undo",
        "state.validation",
        "state.warning",
        "storage.cleanFailed",
        "storage.cleaned",
        "storage.empty",
        "storage.open",
        "storage.unavailable",
        "studio.assetFailed",
        "studio.country",
        "studio.details",
        "studio.logo",
        "studio.none",
        "studio.oneLogo",
        "team.addFailed",
        "team.addForm",
        "team.duplicate",
        "team.empty",
        "team.memberAdded",
        "team.refresh",
        "team.removeConfirm",
        "team.removeOffline",
        "team.rolePicker",
        "transfers.empty",
        "update.available",
        "update.checkFailed",
        "update.downloading",
        "update.later",
        "update.ready",
        "update.required",
        "update.upToDate",
        "upload.backOnline",
        "upload.background",
        "upload.backgroundAsk",
        "upload.creditsLow",
        "upload.done",
        "upload.facesReading",
        "upload.facesReady",
        "upload.failed",
        "upload.keepOpen",
        "upload.manyFailed",
        "upload.morePreparing",
        "upload.noWatermark",
        "upload.offline",
        "upload.outOfCredits",
        "upload.paused",
        "upload.pausedByUser",
        "upload.preparing",
        "upload.resumed",
        "upload.retryAll",
        "upload.retrying",
        "upload.slow",
        "upload.uploading",
        "upload.watermarking",
        "wall.cover",
        "wall.coverFailed",
        "wall.empty",
        "wall.failed",
        "wall.featured",
        "wall.publishConfirm",
        "wall.published",
        "wall.styling",
        "wall.unpublished",
        "watermark.editing",
        "watermark.enabled",
        "watermark.saved",
        "website.aiFailed",
        "website.aiLimit",
        "website.aiUnavailable",
        "website.aiUndone",
        "website.aiWriting",
        "website.aiWritten",
        "website.albumSaved",
        "website.albumUploading",
        "website.albumsEmpty",
        "website.checklist",
        "website.designing",
        "website.dirty",
        "website.discard",
        "website.faviconPending",
        "website.live",
        "website.liveFailed",
        "website.offline",
        "website.published",
        "website.publishing",
        "website.redesign",
        "website.useDesign",
        "website.wizard",
    )
}
