#!/usr/bin/env node
// Generates the moment bindings from spec/mascot.json — no dependencies, no art:
//   packages/kmp/.../MascotMoments.kt      moment-key constants (the code contract)
//   packages/kmp/.../MascotMomentTable.kt  moment → mood/hold/first, and each mood's motion
//   packages/web/src/moments.ts            the same two, for the web
// Usage: node tools/moments.mjs   (or: npm run moments)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SPEC = path.join(ROOT, 'spec/mascot.json');
const KMP_DIR = path.join(ROOT, 'packages/kmp/src/commonMain/kotlin/com/dfeverx/studioshare/mascot');
const WEB_TS = path.join(ROOT, 'packages/web/src/moments.ts');

const spec = JSON.parse(fs.readFileSync(SPEC, 'utf8'));
const moods = Object.keys(spec.moods).sort();
const keys = Object.keys(spec.moments).sort();

// ---- validate -------------------------------------------------------------------------------
const errors = [];
if (!spec.moods.idle) errors.push('moods must include "idle"');
for (const k of keys) {
  const m = spec.moments[k];
  if (!spec.moods[m.mood]) errors.push(`moment ${k}: unknown mood "${m.mood}"`);
  if (!/^[a-z][A-Za-z0-9]*(\.[a-z][A-Za-z0-9]*)+$/.test(k)) errors.push(`moment ${k}: key must be dotted camelCase`);
  if (m.say !== undefined) {
    if (typeof m.say !== 'string' || !m.say.trim()) errors.push(`moment ${k}: say must be a non-empty string`);
    else if (m.say.length > 60) errors.push(`moment ${k}: say must fit the notch (60 characters at most)`);
    if (m.hold) errors.push(`moment ${k}: a held moment can't say anything (it lasts; the notch speaks once)`);
  }
  if (!spec.areas?.[k.split('.')[0]]) errors.push(`moment ${k}: no area label for "${k.split('.')[0]}"`);
}
if (errors.length) {
  console.error(errors.join('\n'));
  process.exit(1);
}

const areas = Object.keys(spec.areas ?? {}).sort();
const quoted = (text) => JSON.stringify(text);
const camel = (key) => key.split('.').map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('');
const header = (by) => `// GENERATED by tools/moments.mjs from spec/mascot.json — do not edit by hand.${by}`;
const write = (file, text) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  console.log(`✓ ${path.relative(ROOT, file)}`);
};

// ---- Kotlin ---------------------------------------------------------------------------------
write(path.join(KMP_DIR, 'MascotMoments.kt'), `${header('')}
// Moment keys are the contract between code and the mascot: append-only, never renamed.
package com.dfeverx.studioshare.mascot

object MascotMoments {
${keys.map((k) => `    const val ${camel(k).replace(/^./, (c) => c.toUpperCase())} = "${k}"`).join('\n')}

    val all: List<String> = listOf(
${keys.map((k) => `        "${k}",`).join('\n')}
    )
}
`);

const ktMoment = (m) => {
  const args = [`"${m.mood}"`];
  if (m.hold) args.push('hold = true');
  if (m.first) args.push(`first = "${m.first}"`);
  if (m.say) args.push(`say = ${quoted(m.say).replace(/\$/g, '\\$')}`);
  return `MascotMomentDef(${args.join(', ')})`;
};
write(path.join(KMP_DIR, 'MascotMomentTable.kt'), `${header('')}
package com.dfeverx.studioshare.mascot

/** Mood name → its body motion (a \`MascotMotion\` id). */
internal val MASCOT_MOOD_MOTIONS: Map<String, String> = mapOf(
${moods.map((m) => `    "${m}" to "${spec.moods[m].motion}",`).join('\n')}
)

/** Moment key → the mood it shows. */
internal val MASCOT_MOMENTS: Map<String, MascotMomentDef> = mapOf(
${keys.map((k) => `    "${k}" to ${ktMoment(spec.moments[k])},`).join('\n')}
)

/** A moment key's first segment → the label the notch card's header shows for it. */
internal val MASCOT_AREAS: Map<String, String> = mapOf(
${areas.map((a) => `    "${a}" to ${quoted(spec.areas[a])},`).join('\n')}
)
`);

// ---- TypeScript -----------------------------------------------------------------------------
const tsMoment = (m) =>
  `{ mood: '${m.mood}'${m.hold ? ', hold: true' : ''}${m.first ? `, first: '${m.first}'` : ''}${m.say ? `, say: ${quoted(m.say)}` : ''} }`;
write(WEB_TS, `${header('')}
// Moment keys are the contract between code and the mascot: append-only, never renamed.
export const MascotMoments = {
${keys.map((k) => `  ${camel(k)}: '${k}',`).join('\n')}
} as const;

export type MascotMoment = (typeof MascotMoments)[keyof typeof MascotMoments];

export interface MascotMomentDef {
  mood: string;
  /** Lasts while its state lasts (hold), rather than playing once. */
  hold?: boolean;
  /** Once-per-account celebration key. */
  first?: string;
  /** The default line a one-off moment says; only moments with one announce themselves. */
  say?: string;
}

/** Mood name → its body motion. */
export const mascotMoodMotions: Record<string, string> = {
${moods.map((m) => `  ${m}: '${spec.moods[m].motion}',`).join('\n')}
};

/** Moment key → the mood it shows. */
export const mascotMomentMoods: Record<string, MascotMomentDef> = {
${keys.map((k) => `  '${k}': ${tsMoment(spec.moments[k])},`).join('\n')}
};

/** The mood for a moment; unknown moments read as idle. */
export function moodForMoment(moment: string): string {
  return mascotMomentMoods[moment]?.mood ?? 'idle';
}

/** A moment key's first segment → the label a notification header shows for it. */
export const mascotAreas: Record<string, string> = {
${areas.map((a) => `  ${a}: ${quoted(spec.areas[a])},`).join('\n')}
};

/** The area label for a moment (e.g. 'upload.done' → 'Upload'). */
export function areaForMoment(moment: string): string {
  return mascotAreas[moment.split('.')[0]] ?? 'StudioShare';
}
`);
