#!/usr/bin/env node
// Generates the moment bindings from spec/mascot.json — no dependencies, no art:
//   packages/kmp/.../MascotMoments.kt      moment-key constants (the code contract)
//   packages/kmp/.../MascotMomentTable.kt  moment → mood/hold/first, and each mood's motion
//   packages/web/src/moments.ts            the same two, for the web
// Usage: node tools/moments.mjs   (or: npm run moments)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SPEC = path.join(ROOT, 'spec/mascot.json');
const KMP_DIR = path.join(ROOT, 'packages/kmp/src/commonMain/kotlin/com/dfeverx/studioshare/mascot');
const WEB_TS = path.join(ROOT, 'packages/web/src/moments.ts');

const spec = JSON.parse(fs.readFileSync(SPEC, 'utf8'));
const moods = Object.keys(spec.moods).sort();
const keys = Object.keys(spec.moments).sort();

// ---- validate -------------------------------------------------------------------------------
const errors = [];
if (!spec.moods.idle) errors.push('moods must include "idle"');
for (const k of keys) {
  const m = spec.moments[k];
  if (!spec.moods[m.mood]) errors.push(`moment ${k}: unknown mood "${m.mood}"`);
  if (!/^[a-z][A-Za-z0-9]*(\.[a-z][A-Za-z0-9]*)+$/.test(k)) errors.push(`moment ${k}: key must be dotted camelCase`);
}
if (errors.length) {
  console.error(errors.join('\n'));
  process.exit(1);
}

const camel = (key) => key.split('.').map((p, i) => (i === 0 ? p : p[0].toUpperCase() + p.slice(1))).join('');
const header = (by) => `// GENERATED by tools/moments.mjs from spec/mascot.json — do not edit by hand.${by}`;
const write = (file, text) => {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  console.log(`✓ ${path.relative(ROOT, file)}`);
};

// ---- Kotlin ---------------------------------------------------------------------------------
write(path.join(KMP_DIR, 'MascotMoments.kt'), `${header('')}
// Moment keys are the contract between code and the mascot: append-only, never renamed.
package com.dfeverx.studioshare.mascot

object MascotMoments {
${keys.map((k) => `    const val ${camel(k).replace(/^./, (c) => c.toUpperCase())} = "${k}"`).join('\n')}

    val all: List<String> = listOf(
${keys.map((k) => `        "${k}",`).join('\n')}
    )
}
`);

const ktMoment = (m) => {
  const args = [`"${m.mood}"`];
  if (m.hold) args.push('hold = true');
  if (m.first) args.push(`first = "${m.first}"`);
  return `MascotMomentDef(${args.join(', ')})`;
};
write(path.join(KMP_DIR, 'MascotMomentTable.kt'), `${header('')}
package com.dfeverx.studioshare.mascot

/** Mood name → its body motion (a \`MascotMotion\` id). */
internal val MASCOT_MOOD_MOTIONS: Map<String, String> = mapOf(
${moods.map((m) => `    "${m}" to "${spec.moods[m].motion}",`).join('\n')}
)

/** Moment key → the mood it shows. */
internal val MASCOT_MOMENTS: Map<String, MascotMomentDef> = mapOf(
${keys.map((k) => `    "${k}" to ${ktMoment(spec.moments[k])},`).join('\n')}
)
`);

// ---- TypeScript -----------------------------------------------------------------------------
const tsMoment = (m) =>
  `{ mood: '${m.mood}'${m.hold ? ', hold: true' : ''}${m.first ? `, first: '${m.first}'` : ''} }`;
write(WEB_TS, `${header('')}
// Moment keys are the contract between code and the mascot: append-only, never renamed.
export const MascotMoments = {
${keys.map((k) => `  ${camel(k)}: '${k}',`).join('\n')}
} as const;

export type MascotMoment = (typeof MascotMoments)[keyof typeof MascotMoments];

export interface MascotMomentDef {
  mood: string;
  /** Lasts while its state lasts (hold), rather than playing once. */
  hold?: boolean;
  /** Once-per-account celebration key. */
  first?: string;
}

/** Mood name → its body motion. */
export const mascotMoodMotions: Record<string, string> = {
${moods.map((m) => `  ${m}: '${spec.moods[m].motion}',`).join('\n')}
};

/** Moment key → the mood it shows. */
export const mascotMomentMoods: Record<string, MascotMomentDef> = {
${keys.map((k) => `  '${k}': ${tsMoment(spec.moments[k])},`).join('\n')}
};

/** The mood for a moment; unknown moments read as idle. */
export function moodForMoment(moment: string): string {
  return mascotMomentMoods[moment]?.mood ?? 'idle';
}
`);
